# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line,
# check the file to be excluded from version control.
# android.R8.usage=androidstudio

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and does not include resources from libraries it depends on.
android.nonTransitiveRClass=true
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
